version: '2.2'
services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: es-node1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.18.0.2,172.18.0.3,172.19.0.2,172.19.0.3,172.19.0.4"
      - "node.attr.network=es-netA"
      - "cluster.routing.allocation.awareness.attributes=network"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      es-netA:
        ipv4_address: 172.18.0.2
  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: es-node2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.18.0.2,172.18.0.3,172.19.0.2,172.19.0.3,172.19.0.4"
      - "node.attr.network=es-netA"
      - "cluster.routing.allocation.awareness.attributes=network"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      es-netA:
        ipv4_address: 172.18.0.3
  es-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: es-node3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.18.0.2,172.18.0.3,172.19.0.2,172.19.0.3,172.19.0.4"
      - "node.attr.network=es-netB"
      - "cluster.routing.allocation.awareness.attributes=network"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9201:9200
    networks:
      es-netB:
        ipv4_address: 172.19.0.2
  es-node4:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: es-node4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.18.0.2,172.18.0.3,172.19.0.2,172.19.0.3,172.19.0.4"
      - "node.attr.network=es-netB"
      - "cluster.routing.allocation.awareness.attributes=network"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      es-netB:
        ipv4_address: 172.19.0.3
  es-node5:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: es-node5
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=172.18.0.2,172.18.0.3,172.19.0.2,172.19.0.3,172.19.0.4"
      - "node.attr.network=es-netB"
      - "cluster.routing.allocation.awareness.attributes=network"
      - "discovery.zen.minimum_master_nodes=3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      es-netB:
        ipv4_address: 172.19.0.4

networks:
  es-netA:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
  es-netB:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
