version: '2'
services:
    cache-server:
        image: redis:alpine
        ports:
            - "6379:6379"
    db:
        image: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: sboot
            MYSQL_PASSWORD: sboot
            MYSQL_ROOT_PASSWORD: root
    app1:
        image: boot-exec
        depends_on:
            - db
            - cache-server
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        environment:
            JAR_NAME: "jsug-shop-zero-0.0.1-SNAPSHOT.jar"
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            spring.datasource.url: "jdbc:mysql://db/mydb"
            spring.datasource.username: "sboot"
            spring.datasource.password: "sboot"
            spring.redis.host: "cache-server"
            spring.redis.port: "6379"
    app2:
        image: boot-exec
        ports:
            - "8081:8080"
        volumes:
            - .:/app
        environment:
            JAR_NAME: "jsug-shop-zero-0.0.1-SNAPSHOT.jar"
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            spring.datasource.url: "jdbc:mysql://db/mydb"
            spring.datasource.username: "sboot"
            spring.datasource.password: "sboot"
            spring.redis.host: "cache-server"
            spring.redis.port: "6379"
    app3:
        image: boot-exec
        ports:
            - "8082:8080"
        volumes:
            - .:/app
        environment:
            JAR_NAME: "jsug-shop-zero-0.0.1-SNAPSHOT.jar"
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            spring.datasource.url: "jdbc:mysql://db/mydb"
            spring.datasource.username: "sboot"
            spring.datasource.password: "sboot"
            spring.redis.host: "cache-server"
            spring.redis.port: "6379"
